browser=C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe
telegram=D:\\Telegram Desktop\\Telegram.exe
vscode=C:\\Users\\User\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe
calculator=calc.exe